export const craNodeModules = [
  {
    icon: "cloud",
    label: "localhost:3000",
    items: [
      { icon: "folder", label: "src/components" },
      {
        icon: "folder",
        label: "node_modules",
        items: [
          { icon: "folder", label: "@remix-run/router" },
          { icon: "folder", label: "ansi-html-community" },
          { icon: "folder", label: "core-js-pure" },
          { icon: "folder", label: "css-loader/dist/runtime" },
          { icon: "folder", label: "events" },
          { icon: "folder", label: "feather-icons-react/build" },
          { icon: "folder", label: "html-entities/lib" },
          { icon: "folder", label: "linkify-it" },
          { icon: "folder", label: "localstorage-slim" },
          { icon: "folder", label: "markdown-it" },
          { icon: "folder", label: "mdurl" },
          { icon: "folder", label: "moment" },
          { icon: "folder", label: "object-assign" },
          { icon: "folder", label: "prop-types" },
          { icon: "folder", label: "punycode.js" },
          { icon: "folder", label: "react" },
          { icon: "folder", label: "react-dom" },
          { icon: "folder", label: "react-router" },
          { icon: "folder", label: "react-router-dom" },
          { icon: "folder", label: "scheduler" },
          { icon: "folder", label: "slugify" },
          { icon: "folder", label: "uc.micro" },
        ],
      },
    ],
  },
];
