import type { Metadata } from "next";
import { Bebas_Neue, Permanent_Marker, Open_Sans } from "next/font/google";

import { Desk } from "@/components/Desk";
import { Books } from "@/components/Books";
import { Plant } from "@/components/Plant";
import { Computer } from "@/components/Computer";
import { Title } from "@/components/Title";
import { Coffee } from "@/components/Coffee";
import { ClientKeyboardController } from "@/components/utils/ClientKeyboardController";
import { getCssText, globalCss, styled } from "@/utils/styling";
import { contents } from "@/utils/contents";

const bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const marker = Permanent_Marker({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const openSans = Open_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const globalStyles = globalCss({
  "body, html": {
    margin: 0,
    padding: 0,
    ...bebas.style,
  },

  "*, *:before, *:after": {
    boxSizing: "border-box",
  },

  ".marker": {
    ...marker.style,
  },

  ".sans": {
    ...openSans.style,
  },
});

const Container = styled("div", {
  position: "fixed",
  inset: 0,
  background: "$wall",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  globalStyles();
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body>
        <Container>
          <Desk />
          <Books contents={contents} />
          <Plant contents={contents} />

          <Computer contents={contents} />
          <Title />

          <Coffee contents={contents} />
        </Container>

        <ClientKeyboardController max={contents.length - 1} />
      </body>
    </html>
  );
}
